# Generated by Django 5.2.3 on 2025-07-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course",
            new_name="CourseModel",
        ),
        migrations.RenameModel(
            old_name="Lesson",
            new_name="LessonModel",
        ),
    ]
