# Generated by Django 5.2.4 on 2025-08-10 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodel",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lessonmodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="courses.coursemodel",
            ),
        ),
        migrations.AddField(
            model_name="mcqoptionmodel",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="courses.mcqquestionmodel",
            ),
        ),
        migrations.AddField(
            model_name="quizmodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="courses.coursemodel",
            ),
        ),
        migrations.AddField(
            model_name="quizmodel",
            name="lessons",
            field=models.ManyToManyField(
                related_name="quizzes", to="courses.lessonmodel"
            ),
        ),
        migrations.AddField(
            model_name="mcqquestionmodel",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcq_questions",
                to="courses.quizmodel",
            ),
        ),
        migrations.AddField(
            model_name="shortanswerquestionmodel",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_questions",
                to="courses.quizmodel",
            ),
        ),
    ]
