# Generated by Django 5.2.4 on 2025-07-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_rename_course_coursemodel_rename_lesson_lessonmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[("mcq", "MCQ"), ("short", "Short Answer")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursemodel",
                    ),
                ),
                (
                    "lessons",
                    models.ManyToManyField(
                        related_name="qizes", to="courses.lessonmodel"
                    ),
                ),
            ],
        ),
    ]
