# Generated by Django 5.2.4 on 2025-07-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_quizmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizmodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="courses.coursemodel",
            ),
        ),
        migrations.AlterField(
            model_name="quizmodel",
            name="lessons",
            field=models.ManyToManyField(
                related_name="quizzes", to="courses.lessonmodel"
            ),
        ),
        migrations.AlterField(
            model_name="quizmodel",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("mcq", "MCQ"),
                    ("short", "Short Answer"),
                    ("mixed", "Mixes Questions"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MCQQuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=150)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_questions",
                        to="courses.quizmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQOptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="courses.mcqquestionmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortAnswerQuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=150)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_questions",
                        to="courses.quizmodel",
                    ),
                ),
            ],
        ),
    ]
