# Generated by Django 5.2.4 on 2025-08-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_quizmodel_course_alter_quizmodel_lessons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortanswerquestionmodel",
            name="correct_ans",
            field=models.CharField(blank=True, null=True),
        ),
    ]
