# Generated by Django 5.2.4 on 2025-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_shortanswerquestionmodel_correct_ans"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonmodel",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="lesson_pdfs/"),
        ),
    ]
